### ISSUE TITLE
ImportError: No module named 'driver'

### ISSUE THREAD

**Issue by yanvigdev** [joshuaboniface/respeaker-led#1]
Hello, I have this error in /var/log/syslog when I run: 

`systemctl start respeaker-led.service`

```
daemon.py[1051]: Traceback (most recent call last):
daemon.py[1051]:   File "/srv/respeaker-led/daemon.py", line 10, in <module>
daemon.py[1051]:     from driver import apa102
daemon.py[1051]: ImportError: No module named 'driver'
```

**Comment by joshuaboniface** [comment]
You'll need to install the `apa102` driver via PIP, or manually. Reference: https://github.com/tinue/APA102_Pi/issues/31

**Comment by yanvigdev** [comment]
I tried to install this module as shown:

```
git clone https://github.com/tinue/APA102_Pi.git
cd ./APA102_Pi
pip3 install .
```
But unfortunately I have this error message

```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==18.0' distribution was not found and is required by the application

```
So I tried this 

```
cd ./APA102_Pi
pip install .
```

but I also have a mistake.

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /root/APA102_Pi
    Complete output from command python setup.py egg_info:
    This package requires the Adafruit_Python_GPIO library to be installed. See https://github.com/adafruit/Adafruit_Python_GPIO for installation instructions.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-4YnBoD/
```
